services:
  server: # nginx - 요청을 받고 PHP interpreter를 트리거
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # https://hub.docker.com/_/nginx → Customize configuration 부분 참고
  # php: # PHP, Laravel 코드 실행
  # mysql:
  # composer:
  # artisan:
  # npm:
